# -*- coding: utf-8 -*-
"""A4.ipynb

Automatically generated by Colab.

"""
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

data = pd.read_csv('Mall_Customers.csv')
data = data.drop('CustomerID', axis=1)
data['Gender'] = data['Gender'].map({'Male': 1, 'Female': 0})
print(data.head())

scaler = StandardScaler()

features = ["Gender","Age", "Annual Income (k$)", "Spending Score (1-100)"]

scaled = scaler.fit_transform(data[features])

scaled_data = pd.DataFrame(scaled, columns = features)

# print(scaled_data.head())

st.dataframe(scaled_data,  use_container_width=True)

#elbow curve
k = range(1, 10)
inert = []
for element in k:
  kmeans = KMeans(n_clusters = element, init = 'k-means++')
  kmeans.fit(scaled_data)
  inert.append(kmeans.inertia_)

plt.plot(k, inert)
plt.xlabel('k value')
plt.ylabel('inertia')
plt.title('elbow method')
plt.show()

kmeans = KMeans(n_clusters = 3, init="k-means++")
kmeans.fit(scaled_data)

labels = kmeans.labels_

scaled_data['cluster'] = labels

print(scaled_data.head())

plt.figure(figsize=(8,6))
plt.scatter(data['Age'], data['Spending Score (1-100)'], c=scaled_data['cluster'], cmap = 'plasma')
plt.xlabel('Age')
plt.ylabel('Spending Score')
plt.title('Spending Score vs Age')
plt.colorbar(label='Cluster')
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(data['Gender'], data['Spending Score (1-100)'], c=scaled_data['cluster'], cmap = 'plasma')
plt.xlabel('Gender')
plt.ylabel('Spending Score')
plt.title('Spending Score vs Gender')
plt.colorbar(label='Cluster')
plt.show()

plt.figure(figsize=(8,6))
plt.scatter(data['Annual Income (k$)'], data['Spending Score (1-100)'], c=scaled_data['cluster'], cmap = 'plasma')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score')
plt.title('Spending Score vs Annual Income (k$)')
plt.colorbar(label='Cluster')
plt.show()
